hydra_ros_node:
  ros__parameters:
    input:
      type: RosInput
      tf_verbosity: 1
      clear_queue_on_fail: true
      inputs:
        left_cam:
          receiver:
            type: ClosedSetImageReceiver
          sensor:
            type: camera_info
            min_range: $(var sensor_min_range)
            max_range: $(var sensor_max_range)
            extrinsics:
              type: ros
